Section "Device"
    Identifier "Intel"
    Driver     "modesetting"
    Option     "AccelMethod" "none"
EndSection
Section "Screen"
    Identifier "Default"
    Device     "Intel"
EndSection
Section "ServerLayout"
    Identifier "Default"
    Screen     0 "Default" 0 0
    Option     "AutoAddDevices" "true"
EndSection
Section "ServerFlags"
    Option     "AutoEnableDevices" "true"
    Option     "AutoAddGPU" "true"
EndSection